package com.darshit.billsplitter.utils

import android.content.Context
import android.content.Intent
import com.darshit.billsplitter.data.model.Bill
import com.darshit.billsplitter.data.model.Participant
import com.darshit.billsplitter.data.model.SettlementTransaction

object ExportUtils {

    fun buildBillSummaryText(
        bill: Bill,
        participants: List<Participant>,
        transactions: List<SettlementTransaction>,
        currencySymbol: String
    ): String {
        val sb = StringBuilder()
        sb.appendLine("━━━━━━━━━━━━━━━━━━━━━━━━")
        sb.appendLine("    BILL SPLITTER SUMMARY")
        sb.appendLine("━━━━━━━━━━━━━━━━━━━━━━━━")
        sb.appendLine()
        sb.appendLine("📋 Bill: ${bill.title}")
        if (bill.description.isNotBlank()) {
            sb.appendLine("📝 Note: ${bill.description}")
        }
        sb.appendLine("📅 Date: ${DateUtils.formatDate(bill.date)}")
        sb.appendLine("🏷️ Category: ${bill.category}")
        sb.appendLine("💰 Total: ${CurrencyUtils.formatAmount(bill.totalAmount, currencySymbol)}")
        sb.appendLine("👤 Paid by: ${bill.paidByName}")
        sb.appendLine("🔀 Split: ${bill.splitType}")
        sb.appendLine()
        sb.appendLine("── PARTICIPANTS ──")
        participants.forEach { p ->
            val status = if (p.isPaid) "✅" else "⏳"
            sb.appendLine("$status ${p.name}: ${CurrencyUtils.formatAmount(p.shareAmount, currencySymbol)}")
        }
        sb.appendLine()
        if (transactions.isNotEmpty()) {
            sb.appendLine("── SETTLEMENTS ──")
            transactions.forEach { t ->
                val status = if (t.isSettled) "✅ PAID" else "⏳ PENDING"
                sb.appendLine("${t.fromParticipant} → ${t.toParticipant}: ${CurrencyUtils.formatAmount(t.amount, currencySymbol)} [$status]")
            }
            sb.appendLine()
        }
        sb.appendLine("━━━━━━━━━━━━━━━━━━━━━━━━")
        sb.appendLine("Generated by Bill Splitter")
        sb.appendLine("Developed by Darshit")
        return sb.toString()
    }

    fun shareBillSummary(context: Context, summaryText: String, billTitle: String) {
        val intent = Intent(Intent.ACTION_SEND).apply {
            type = "text/plain"
            putExtra(Intent.EXTRA_SUBJECT, "Bill Summary: $billTitle")
            putExtra(Intent.EXTRA_TEXT, summaryText)
        }
        context.startActivity(Intent.createChooser(intent, "Share Bill Summary"))
    }
}
